#!/bin/sh
# CARD_DATA should refer to the directory in which Carmine Impact data files are placed.
#CARD_DATA=~/cardboard
#CARD_DATA=/usr/local/cardboard
CARD_DATA=.

# CARD_BIN should refer to the directory in which Carmine Impact executable files are placed.
CARD_BIN=${CARD_DATA}/bin_unix

# CARD_OPTIONS contains any command line options you would like to start Carmine Impact with.
#CARD_OPTIONS="-f"
CARD_OPTIONS="-q${HOME}/.cardboard -cOFFLINE"

# SYSTEM_NAME should be set to the name of your operating system.
#SYSTEM_NAME=Linux
SYSTEM_NAME=`uname -s`

# MACHINE_NAME should be set to the name of your processor.
#MACHINE_NAME=i686
MACHINE_NAME=`uname -m`

case ${SYSTEM_NAME} in
Linux)
  SYSTEM_NAME=linux_
  ;;
*)
  SYSTEM_NAME=unknown_
  ;;
esac

case ${MACHINE_NAME} in
i486|i586|i686)
  MACHINE_NAME=
  ;;
x86_64|amd64)
  MACHINE_NAME=64_
  ;;
*)
  if [ ${SYSTEM_NAME} != native_ ]
  then
    SYSTEM_NAME=native_
  fi
  MACHINE_NAME=
  ;;
esac

if [ -x ${CARD_BIN}/native_client ]
then
  SYSTEM_NAME=native_
  MACHINE_NAME=
fi

if [ -x ${CARD_BIN}/${SYSTEM_NAME}${MACHINE_NAME}client ]
then
  cd ${CARD_DATA}
  exec ${CARD_BIN}/${SYSTEM_NAME}${MACHINE_NAME}client ${CARD_OPTIONS} "$@"
else
  echo "Your platform does not have a pre-compiled Cardboard Engine client."
  echo "Please follow the following steps to build a native client:"
  echo "1) Ensure you have the SDL2, SDL2-image, SDL2-mixer, SDL2-ttf, and OpenGL libraries installed."
  echo "2) Change directory to src/ and type \"make install\"."
  echo "3) If the build succeeds, return to this directory and run this script again."
  exit 1
fi

